apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001  # Choose an available port between 30000-32767
  selector:
    app: app
